[package]
name = "traj-propagate"
version = "0.0.1"
authors = ["pixldemon <moritzamando@protonmail.com>"]
edition = "2018"

[dependencies]
rust-spice = "0.7.1"
ndarray = "0.15.4"
clap = { version = "3.0.0-rc.1", features = [ "derive" ] }
serial_test = "0.6.0"
